add TAMP register block for g0, g4, l5, u5 and wl
embassy-rs/stm32-data pull request #267
Opened 2023-09-27 06:01 UTC by oll3

Adds TAMP register block for the devices where I could understand how it was mapped. Some devices seems to have their TAMP/backup/RTC more intertwined and not as a separate register block. Those are not included.

Also not really sure why only u5 and l5 was mapped automatically while I had to add them manually for g0, g4 and wl through extra/families. I guess some field is missing in one of the sources?

Mainly adding this for gaining access to backup registers. Tested on stm32wle5cc.

2023-09-27 22:41 UTC, xoviat commented
Have you looked in the source files to see why chips.rs is not picking it up?


https://embassy.dev/book/dev/developer_stm32.html

2023-09-28 06:49 UTC, oll3 commented
Seems `InstanceName="TAMP"` is not present in many of the xmls where the corresponding `TAMP` block is present in the svd.
Eg `stm32wle5.svd` has a `TAMP` peripheral but no  `InstanceName="TAMP"`  in `STM32WLE5CCUx.xml`.

How should this be handled?

2023-09-28 20:32 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat requested changes
any fields, etc that have a number suffix need to be consolidated to an array. see the hrtim_v1.yaml for examples of this.

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:35 UTC, xoviat commented on data/registers/tamp_g0.yaml
> +      bit_size: 1
consolidate to an array

2023-09-28 20:36 UTC, xoviat commented
> How should this be handled?

If it's not in the XML, you've done the right thing. I will merge after you arrayize the fields, per the review.

2023-09-28 20:55 UTC, xoviat commented
> I will merge after you arrayize the fields, per the review.

Also, to be clear I mean all of the files. Not just the one I reviewed.

2023-09-29 06:10 UTC, oll3 commented
> any fields, etc that have a number suffix need to be consolidated to an array. see the hrtim_v1.yaml for examples of this.

I see, though many of these fields have flags which are not fully sequential. Should they be merged to arrays anyway?

Eg. ITAMPxIE from `tamp_wl.yaml` has flags on bits 18, 20, 21, 23:
```yaml
    - name: ITAMP3IE
      description: Internal tamper 3 interrupt enable
      bit_offset: 18
      bit_size: 1
    - name: ITAMP5IE
      description: Internal tamper 5 interrupt enable
      bit_offset: 20
      bit_size: 1
    - name: ITAMP6IE
      description: Internal tamper 6 interrupt enable
      bit_offset: 21
      bit_size: 1
    - name: ITAMP8IE
      description: Internal tamper 8 interrupt enable
      bit_offset: 23
      bit_size: 1
```

As an array I guess it would look like this, ignoring that offset 19 and 22 are not valid:
```yaml
    - name: ITAMPIE
      description: Internal tamper 3 interrupt enable
      bit_offset: 18
      bit_size: 1
      array:
        len: 6
        stride: 1
```

2023-09-29 14:23 UTC, xoviat commented
Use offsets in that case. Again, see hrtim for an example.

2023-09-30 00:43 UTC, Dirbaio commented
In this case the bit offsets line up nicely with the numbers, it's just that there's "holes" because some bits are unimplemented. In this case, just use a normal array. it's OK if you can write to the unimplemented bits, these are typically ignored anyway.

only use offsets if the bits really don't line up. For example if there was this:
- ITAMP1IE on bit 8
- ITAMP2IE on bit 9
- ITAMP3IE on bit 16
- ITAMP4IE on bit 17

2023-10-02 05:29 UTC, oll3 commented
> In this case the bit offsets line up nicely with the numbers, it's just that there's "holes" because some bits are unimplemented. In this case, just use a normal array. it's OK if you can write to the unimplemented bits, these are typically ignored anyway.
> 
> (using offsets would prevent writing to unimplemented bits, but then it no longer holds that TAMPn is at index n-1, which is confusing)
> ...

Makes sense!

I have made repeated fields into arrays and also removed some more 1 bit enums which seemed fairly obvious. And renamed some enums with confusing names (mainly for u5).

Thank you both for taking the time to review and the guidance, really appreciate it! :star2:

2023-10-02 20:20 UTC, xoviat approved these changes

2023-10-02 20:22 UTC, xoviat commented
bender run

2023-10-02 21:04 UTC, merged